#!/usr/bin/env python3
"""
Find images whose background is transparent rather than painted.

Tiles sit on a white card, so a logo delivered as a mark on transparency has
nothing to sit against — it bleeds into the tile and reads as floating. Those
need a white plate and some breathing room, which is a per-image fact the
component cannot work out on its own.

Detected here rather than at build time: it is pixel work over ~450 files and
the answer only changes when the assets do. Re-run after adding artwork:

    python3 scripts/detect-transparent.py

Writes src/data/transparent.ts.
"""

import glob
import os

from PIL import Image

Image.MAX_IMAGE_PIXELS = None

ROOT = os.path.join(os.path.dirname(__file__), '..')
ASSETS = os.path.join(ROOT, 'src/assets/work')
OUT = os.path.join(ROOT, 'src/data/transparent.ts')

# Share of pixels that must be clear before an image counts as background-less.
# A drop shadow or a rounded corner clears a few percent; a mark on transparency
# clears most of the frame.
THRESHOLD = 0.10


def clear_fraction(path: str) -> float:
    im = Image.open(path)
    if im.mode not in ('RGBA', 'LA', 'P'):
        return 0.0
    alpha = im.convert('RGBA').getchannel('A').resize((96, 96), Image.BILINEAR)
    px = list(alpha.getdata())
    return sum(1 for v in px if v < 32) / len(px)


def main() -> None:
    names = []
    for path in sorted(glob.glob(os.path.join(ASSETS, '**/*.*'), recursive=True)):
        if os.path.splitext(path)[1].lower() not in ('.png', '.webp', '.gif'):
            continue
        try:
            if clear_fraction(path) > THRESHOLD:
                names.append(os.path.basename(path))
        except Exception as exc:  # a corrupt file should not fail the whole run
            print(f'  skipped {os.path.basename(path)}: {exc}')

    body = '\n'.join(f"  '{n}'," for n in names)
    with open(OUT, 'w') as fh:
        fh.write(
            '/* Generated by scripts/detect-transparent.py — do not edit by hand.\n'
            '   Images whose background is transparent, so a tile has to supply\n'
            '   a white plate and padding for them to read. */\n\n'
            'export const transparent = new Set<string>([\n'
            f'{body}\n'
            ']);\n'
        )
    print(f'{len(names)} transparent-background image(s) -> src/data/transparent.ts')


if __name__ == '__main__':
    main()
