/* Generated by scripts/detect-transparent.py — do not edit by hand.
   Images whose background is transparent, so a tile has to supply
   a white plate and padding for them to read. */

export const transparent = new Set<string>([
  'bilflo-display-ads-01-bilflo-ad-1.png',
  'bilflo-display-ads-06-bilflo-ad-6.png',
  'logos-marks-01-simplee-coffee-1.png',
  'logos-marks-add-05-eg-lockup-xl.png',
  'logos-marks-add-06-revd-up-lockup-vertical-light-xl.webp',
  'amtec-illustration-05-water-cooler-d1.png',
  'amtec-illustration-07-biq-cover.png',
  'hiring-scott-01-hiring-scott-logo-final-green.png',
]);
